### ISSUE TITLE
Add kf-deberta-multitask

### ISSUE THREAD

**Issue by vkehfdl1** [Marker-Inc-Korea/AutoRAG-example-korean-embedding-benchmark#1]
Huggingface에 배포된 모델들 중에선 kf-deberta-multitask 모델이 제가 테스트 해봤을때는 가장 우수했는데, 해당 모델도 같은 세팅에서 실험 부탁드려도 될까요?🙏

upskyy/kf-deberta-multitask

**Comment by yjoonjang** [comment]
안녕하세요. 평소 AutoRAG에 굉장히 관심이 많고, 블로그 포스트를 즐겨 보는 학생입니다.
먼저 좋은 임베딩모델 평가 모델을 제공해 주신 Marker, Allganize에게 감사의 인사 드립니다. 🙇‍♂️🙇‍♂️

다름이 아니고 최근에 저희 연구실에서 임베딩모델을 개발한 후, 모델을 평가해보고자 Marker 회사에서 만든 벤치마크를 활용하게 되었습니다.
그러면서 issue에 올라온 upskyy/kf-deberta-multitask 모델도 함께 평가를 진행했는데, 혹시나 도움이 될까 하여 결과를 공유드립니다.
[summary.csv](https://github.com/user-attachments/files/16541448/summary.csv)

- 또, 저희 연구실에서 개발한 모델은 현재 private repository에 등록된 비공개 모델인데, 혹시 본 모델의 결과물을 공유드리면 올려주실 수 있는지, 만일 비공개 모델이라 제약이 많다면 결과를 공유드릴 다른 방도가 있을 지 여쭙니다.

다시 한번 좋은 벤치마크를 공유해 주셔서 감사합니다.

**Comment by vkehfdl1** [comment]
@yjoonjang 
일단, 모델 결과 제공에 감사드립니다. README 및 YAML & main.py에 반영하도록 하겠습니다.

+ 비공개 모델에 대한 결과 자체는 README에 올려드릴 수 있을 것 같습니다. 
평가 결과 공유해주시면 README에 비공개 모델임을 공지하고 기재하도록 하겠습니다.
다만, 누구나 public하게 사용 가능한 모델이 아니라면 AutoRAG를 통한 실행이 가능하도록 만드는 것에는 한계가 있지 않을까 싶네요.
혹시 public하게 사용 가능한 api나 방식이 제공된다면 해당 벤치마크 레포에서 바로 실행하도록 바꿀 수 있지 않을까 싶습니다^^

**Comment by yjoonjang** [comment]
안녕하세요 @vkehfdl1 , 답변 주셔서 정말 감사합니다.
말씀주신 README, YAML, main.py 파일을 첨부하여 PR 생성해 두었습니다.

말씀하신대로, AutoRAG에서도 사용할 수 있도록 가능한 public으로 공개할 수 있는 방법을 생각해 보겠습니다. 
다시 한번 감사드립니다.

**Comment by vkehfdl1** [comment]
close at #2
